redis:
  host: 127.0.0.1:6379
  user:
  password:
  db: 4
  socket_timeout: 2
sql:
  host: 127.0.0.1
  port: 5432
  user: root
  password: 123456
  db: notification
  pool_recycle: 3600
  engine: postgresql
influxdb:
  host: 127.0.0.1
  port: 8086
  org: my-org
  token: my-super-influxdb-auth-token
  bucket: notification
testSQL:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: notification_test
  pool_recycle: 3600


server:
  port: 9380
  g_port: 59380
  rear_timeout: 300  # s
  write_timeout: 300  # s
  is_initial: True
  smtp_tls: True
  smtp_server: smtp.gmail.com
  smtp_port: 25
  smtp_proxy_type:
  smtp_proxy_host:
  smtp_proxy_port:
  smtp_user: sammy.sheu@nadisystem.com
  smtp_password: pdtuyubxdtnaambj

  account_server: http://127.0.0.1:9322
  super_token: 57at3klp0y192aecwc

  system_log_g_server: 127.0.0.1:59360
  system_log_r_server: http://127.0.0.1:9360
  system_log_enable: true

